version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  mandaten:
    image: lblod/frontend-mandatendatabank:0.10.7
    links:
      - identifier:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.7.0
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.6.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.19.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  filehost:
    image: nginx:1.15.2
    volumes:
      - ./data/exports:/data/exports
      - ./config/filehost:/etc/nginx/conf.d
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  import:
    image: lblod/mandaten-import-service:0.3.1
    links:
      - virtuoso:database
    volumes:
      - ./data/imports:/data/imports # map to actual directory on your system
    environment:
      CRON_PATTERN: "0 5 * * *"
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  export:
    image: lblod/mandaten-download-generator-service:0.3.3
    environment:
      EXPORT_CRON_PATTERN: "0 0 6 * * *"
    volumes:
      - ./data/exports:/data/exports
      - ./config/export:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  sitemap:
    image: lblod/sitemap-service:0.2.1
    volumes:
      - ./config/sitemap/:/config/
      - ./data/sitemap/:/data/
    environment:
      SITEMAP_MAX_AGE: 5
    links:
      - virtuoso:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
