version: '3.4'
services:
  mandaten:
    image: lblod/frontend-mandatendatabank:0.2.2
    links:
      - identifier:backend
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  identifier:
    image: semtech/mu-identifier:1.3.0
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  database:
    image: tenforce/virtuoso:1.3.0-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  migrations:
    image: semtech/mu-migrations-service:0.3.0
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  cache:
    image: semtech/mu-cache:0.5.0
    environment:
      CACHE_BACKEND: http://resource/
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  resource:
    image: semtech/mu-cl-resources:1.16.0
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  filehost:
    image: nginx:1.13
    volumes:
      - ./data/exports:/data/exports
      - ./config/filehost:/etc/nginx/conf.d
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  export:
    image: lblod/mandaten-download-generator-service:0.1.0
    environment:
      EXPORT_CRON_PATTERN: "0 0 0 * * *"
    volumes:
      - ./data/exports:/data/exports
      - ./config/export:/config
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

