version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  mandaten:
    image: lblod/frontend-mandatendatabank:0.7.0
    links:
      - identifier:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.4.0
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  database:
    image: tenforce/virtuoso:1.3.0-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.3.1
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  cache:
    image: semtech/mu-cache:0.5.0
    environment:
      CACHE_BACKEND: http://resource/
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.17.1
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  filehost:
    image: nginx:1.15.2
    volumes:
      - ./data/exports:/data/exports
      - ./config/filehost:/etc/nginx/conf.d
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  import:
    image: lblod/mandaten-import-service:0.1.1
    volumes:
      - ./data/imports:/data/imports # map to actual directory on your system
    environment:
      CRON_PATTERN: "0 5 * * *"
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  export:
    image: lblod/mandaten-download-generator-service:0.3.0
    environment:
      EXPORT_CRON_PATTERN: "0 0 6 * * *"
    volumes:
      - ./data/exports:/data/exports
      - ./config/export:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging

