version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  mandaten:
    image: lblod/frontend-mandatendatabank:0.14.1
    links:
      - identifier:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.9.0
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  database:
    image: cecemel/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "true"
      # Note: not sure wether it does something, it is meant for healing-process which may make
      # heavy queries
      QUERY_MAX_PROCESSING_TIME: 605000
      QUERY_MAX_EXECUTION_TIME: 605000
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  delta-notifier:
    image: cecemel/delta-notifier:0.2.0-beta.2
    volumes:
      - ./config/delta:/config
      - ./data/delta/queues:/queues
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini # Note: on production override this setting
      - ./config/virtuoso/:/opt/virtuoso-scripts
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.6.0
    environment:
      MU_SPARQL_TIMEOUT: '300'
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.19.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  filehost:
    image: nginx:1.15.2
    volumes:
      - ./data/exports:/data/exports
      - ./config/filehost:/etc/nginx/conf.d
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  export:
    image: lblod/mandaten-download-generator-service:0.3.6
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
      EXPORT_CRON_PATTERN: "0 0 6 * * *"
    volumes:
      - ./data/exports:/data/exports
      - ./config/export:/config
    links:
      - virtuoso:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  sitemap:
    image: lblod/sitemap-service:0.2.1
    volumes:
      - ./config/sitemap/:/config/
      - ./data/sitemap/:/data/
    environment:
      SITEMAP_MAX_AGE: 5
    links:
      - virtuoso:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.1
    volumes:
      - ./data/files:/share
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  deliver-email-service:
    image: redpencil/deliver-email-service:0.2.0
    environment:
      MAILBOX_URI: 'http://data.lblod.info/id/mailboxes/1'
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
################################################################################
# DELTAS
################################################################################
  delta-producer-report-generator:
    image: lblod/delta-producer-report-generator:0.3.0
    environment:
      OUTBOX: "http://data.lblod.info/id/mail-folders/2"
    volumes:
      - ./config/delta-producer-consumer/report-generator:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  mandatendatabank-consumer:
    image: lblod/delta-consumer:0.1.4
    environment:
      DCR_SYNC_BASE_URL: 'https://loket.lblod.info' # replace with link to Loket API
      DCR_SERVICE_NAME: 'mandatendatabank-consumer'
      DCR_SYNC_FILES_PATH: '/sync/mandatarissen/files'
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/MandatarissenCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/mandatarissen"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/sync/mandatarissen"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/mandatendatabank-consumer"
      DCR_DELTA_JOBS_RETENTION_PERIOD: 15
      BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: 'true'
      DCR_KEEP_DELTA_FILES: 'true'
      DCR_DISABLE_INITIAL_SYNC: 'true'
      INGEST_GRAPH: "http://mu.semte.ch/graphs/public"
      SLEEP_BETWEEN_BATCHES: 100
      DCR_BATCH_SIZE: 10000 # TODO: this is confusing bit in the API -> refers to the chunks of the read stream of the dumpfile of the intiial sync
      BATCH_SIZE: 10000 # TODO: this is confusing bit in the API -> refers to the chunks of the ingestion in the database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  op-public-consumer:
    image: lblod/delta-consumer:0.1.4
    environment:
      DCR_SERVICE_NAME: "op-public-consumer"
      DCR_SYNC_BASE_URL: "https://organisaties.abb.lblod.info" # replace with link to OP API
      DCR_SYNC_FILES_PATH: "/sync/public/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/PublicCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/op-public"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/deltaSync/op-public"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/op-public-consumer"
      DCR_DISABLE_INITIAL_SYNC: "true"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_JOBS_RETENTION_PERIOD: "30"
      DCR_ENABLE_TRIPLE_REMAPPING: "true"
      DCR_LANDING_ZONE_GRAPH: "http://mu.semte.ch/graphs/landing-zone/op-public"
      DCR_REMAPPING_GRAPH: "http://mu.semte.ch/graphs/public"
      DCR_BATCH_SIZE: 1000
      SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES: "404,500,503"
      SUDO_QUERY_RETRY: "true"
    volumes:
      - ./config/delta-consumers/op-consumer/mapping:/config/mapping
      - ./data/files/consumer-files/op-public:/consumer-files/
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
################################################################################
# END DELTAS
################################################################################
