version: '3.4'
services:
  loket:
    image: lblod/frontend-loket
    links:
      - identifier:backend
  mandaten:
    image: lblod/frontend-mandatendatabank:0.1.0
    links:
      - identifier:backend
  identifier:
    image: semtech/mu-identifier:1.3.0
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.3.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  migrations:
    image: semtech/mu-migrations-service:0.3.0
    volumes:
      - ./config/migrations:/data/migrations
  cache:
    image: semtech/mu-cache:0.5.0
    environment:
      CACHE_BACKEND: http://resource/    
  resource:
    image: semtech/mu-cl-resources:1.16.0
    volumes:
      - ./config/resources:/config
  filehost:
    image: nginx:1.13
    volumes:
      - ./data/exports:/data/exports
      - ./config/filehost:/etc/nginx/conf.d
  export:
    image: lblod/mandaten-download-generator-service:0.1.0
    environment:
      EXPORT_CRON_PATTERN: "0 0 0 * * *"
    volumes:
      - ./data/exports:/data/exports
      - ./config/export:/config
