DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/MandatarisStatusCode> ;
       ?p ?o.
    VALUES ?p {
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/2004/02/skos/core#prefLabel>
        <http://www.w3.org/2004/02/skos/core#scopeNote>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BeleidsdomeinCode> ;
       ?p ?o.
    VALUES ?p {
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/2004/02/skos/core#prefLabel>
        <http://www.w3.org/2004/02/skos/core#scopeNote>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> {
    ?s a <http://data.vlaanderen.be/ns/mandaat#Mandataris> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://data.vlaanderen.be/ns/mandaat#start>
        <http://data.vlaanderen.be/ns/mandaat#einde>
        <http://data.vlaanderen.be/ns/mandaat#rangorde>
        <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan>
        <http://www.w3.org/ns/org#holds>
        <http://data.vlaanderen.be/ns/mandaat#status>
        <http://data.vlaanderen.be/ns/mandaat#isTijdelijkVervangenDoor>
        <http://data.vlaanderen.be/ns/mandaat#beleidsdomein>
        <http://www.w3.org/ns/org#hasMembership>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> {
    ?s a <http://www.w3.org/ns/person#Person> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://xmlns.com/foaf/0.1/familyName>
        <http://xmlns.com/foaf/0.1/name>
        <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam>
        <http://www.w3.org/2002/07/owl#sameAs>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> {
    ?s a <http://www.w3.org/ns/org#Membership> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/ns/org#organisation>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/lmb/mandaten/public> {
    ?s a <http://data.vlaanderen.be/ns/mandaat#Fractie> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <https://www.w3.org/ns/regorg#legalName>
        <http://www.w3.org/ns/org#memberOf>
        <http://www.w3.org/ns/org#linkedTo>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/mandaat#Mandaat> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://data.vlaanderen.be/ns/mandaat#aantalHouders>
        <http://www.w3.org/ns/org#role>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode> ;
       ?p ?o.
    VALUES ?p {
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/2004/02/skos/core#prefLabel>
        <http://www.w3.org/2004/02/skos/core#scopeNote>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://data.vlaanderen.be/ns/mandaat#bindingEinde>
        <http://data.vlaanderen.be/ns/mandaat#bindingStart>
        <http://www.w3.org/ns/org#hasPost>
        <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/2004/02/skos/core#prefLabel>
        <http://data.vlaanderen.be/ns/besluit#bestuurt>
        <http://data.vlaanderen.be/ns/besluit#classificatie>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/2004/02/skos/core#prefLabel>
        <http://www.w3.org/2004/02/skos/core#altLabel>
        <http://data.vlaanderen.be/ns/besluit#classificatie>
        <http://data.vlaanderen.be/ns/besluit#werkingsgebied>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode> ;
       ?p ?o.
    VALUES ?p {
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/2004/02/skos/core#prefLabel>
        <http://www.w3.org/2004/02/skos/core#scopeNote>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> { ?s ?p ?o. }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/prov#Location> ;
       ?p ?o.
    VALUES ?p {
        <http://mu.semte.ch/vocabularies/core/uuid>
        <http://www.w3.org/2000/01/rdf-schema#label>
        <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau>
    }
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a ?type .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a ?type .
    VALUES ?type {
      <http://mu.semte.ch/vocabularies/ext/MandatarisStatusCode>
      <http://mu.semte.ch/vocabularies/ext/BeleidsdomeinCode>
      <http://data.vlaanderen.be/ns/mandaat#Mandataris>
      <http://www.w3.org/ns/person#Person>
      <http://www.w3.org/ns/org#Membership>
      <http://data.vlaanderen.be/ns/mandaat#Fractie>
      <http://data.vlaanderen.be/ns/mandaat#Mandaat>
      <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode>
      <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>
      <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>
      <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>
      <http://www.w3.org/ns/prov#Location>
    }
  }
}
